name: Web

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
     - 'Frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          cd Frontend
          npm install
          CI=''
          npm install env-cmd
          npm run build:testing

      - name: Get DateTime as tag for the container
        id: get_datetime
        run: |
          current_timestamp=$(date +%s)
          formatted_datetime=$(date -u -d "@${current_timestamp}" +"%Y%m%d%H%M%S")
          echo "::set-output name=formatted_datetime::$formatted_datetime"

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy web Container App 
        uses: azure/container-apps-deploy-action@v1 
        with: 
          appSourcePath: ${{ github.workspace }}/Frontend
          dockerfilePath: Dockerfile
          acrName: acraicvscreeningeastusprod
          containerAppName: capps-web-cvscreen-eastus-prod
          resourceGroup: RG-OPENAI
          imageToBuild: acraicvscreeningeastusprod.azurecr.io/poc-web-api:latest

      - name: Deploy the container app 
        uses: azure/cli@v2
        with: 
          cliversion: 2.30.0
          inlineScript: |
            az containerapp update \
              --name capps-web-cvscreen-eastus-prod \
              --resource-group RG-OPENAI \
              --image acraicvscreeningeastusprod.azurecr.io/poc-web-api:latest \
              --cpu 1.0 \
              --memory 2.0Gi \
              --min-replicas 1 \
              --max-replicas 1 \
              --revision-suffix ${{ steps.get_datetime.outputs.formatted_datetime }}        
